import Head from "next/head";
import styles from "@/styles/PageHome.module.css";
import Cards from "@/components/Cards";
import Chips from "@/components/Chips";
import React, { useState } from "react";
import HamburgerMenu from "@/components/HamburgerMenu";
import { NavigationBar } from "@/components/Navigation";
import { SearchBar } from "@/components/SearchBar";
import sampleEvents from "@/public/samples/events";

export default function Home() {
  const [showHamburgerMenu, setShowHamburgerMenu] = useState(false);
  const [filteredEvents, setFilteredEvents] = useState(sampleEvents);
  const [searchTerm, setSearchTerm] = useState("");
  const [activeChip, setActiveChip] = useState("");

  const toggleHamburgerMenu = () => {
    setShowHamburgerMenu(!showHamburgerMenu);
  };

  const handleSearch = (searchTerm) => {
    setSearchTerm(searchTerm);
    setActiveChip(searchTerm);

    const filteredItems = sampleEvents.filter((event) =>
      event.title.toLowerCase().includes(searchTerm.toLowerCase())
    );

    setFilteredEvents(filteredItems);
  };

  return (
    <>
      <Head>
        <title>Eco Findr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.contentWrapper}>
            <img
              src={"/images/hamburgerMenu.png"}
              className={styles.menuIcon}
              width="40px"
              height="auto"
              alt="hamburger menu"
              onClick={toggleHamburgerMenu}
            />
            {showHamburgerMenu && <HamburgerMenu closeMenu={toggleHamburgerMenu} />}
            <SearchBar onSearch={handleSearch} />
            <h3 className={styles.h3}>Categories</h3>
            <div className={styles.chipsWrapper}>
              <div className={styles.chips}>
                <Chips buttonText={"Biking"} onClick={handleSearch} isActive={activeChip === "Biking"} />
                <Chips buttonText={"Outdoor"} onClick={handleSearch} isActive={activeChip === "Outdoor"} />
                <Chips buttonText={"Beach"} onClick={handleSearch} isActive={activeChip === "Beach"} />
                <Chips buttonText={"Hike"} onClick={handleSearch} isActive={activeChip === "Hike"} />
                <Chips buttonText={"Indoor"} onClick={handleSearch} isActive={activeChip === "Indoor"} />
                <Chips buttonText={"Clean Up"} onClick={handleSearch} isActive={activeChip === "Clean Up"} />
                <Chips buttonText={"Gardening"} onClick={handleSearch} isActive={activeChip === "Gardening"} />
              </div>
            </div>
            <h3 className={styles.h3}>Upcoming Events</h3>
            <div className={styles.cards}>
              {filteredEvents.map((event) => (
                <Cards
                  key={event.title}
                  title={event.title}
                  description={event.description}
                  location={event.location}
                  date={event.date}
                  time={event.time}
                  imgSrc={event.imgSrc}
                  alt={event.alt}
                />
              ))}
            </div>
          </div>
          <NavigationBar />
        </div>
      </main>
    </>
  );
}
